type QuestionType = "checkbox" | "radio" | "text";

interface QuestionOption {
	id: string;
	label: string;
	isOther?: boolean;
	isNegative?: boolean;
}

interface Question {
	id: string;
	title: string;
	type: QuestionType;
	options?: QuestionOption[];
}

interface Section {
	id: string;
	title: string;
	description: string;
	questions: Question[];
}

interface Survey {
	id: string;
	title: string;
	year: number;
	sections: Section[];
}

export default {
	id: "1",
	title: "State of Bitcoin",
	year: 2024,
	sections: [
		{
			id: "1",
			title: "Features",
			description: "Usage and experience with Bitcoin protocol features",
			questions: [
				{
					id: "1",
					title: "Which of these Bitcoin features have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Taproot" },
						{ id: "2", label: "SegWit" },
						{ id: "3", label: "DLC (Discrete Log Contracts)" },
						{ id: "4", label: "OP_RETURN" },
						{ id: "5", label: "Schnorr Signatures" },
						{ id: "6", label: "Multi-signature (MultiSig)" },
						{ id: "7", label: "Replace-By-Fee (RBF)" },
						{ id: "8", label: "Time-locked transactions" },
						{ id: "9", label: "Pay-to-Script-Hash (P2SH)" },
						{ id: "10", label: "Native SegWit (bech32)" },
						{ id: "11", label: "Nested SegWit" },
						{ id: "12", label: "Miniscript" },
						{ id: "13", label: "Other", isOther: true },
						{ id: "14", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title:
						"What are your primary motivations for exploring these features?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Privacy" },
						{ id: "2", label: "Transaction cost reduction" },
						{ id: "3", label: "Smart contract development" },
						{ id: "4", label: "Building payment solutions" },
						{ id: "5", label: "Personal curiosity and experimentation" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "How frequently do you use these Bitcoin features?",
					type: "radio",
					options: [
						{ id: "1", label: "Daily" },
						{ id: "2", label: "Weekly" },
						{ id: "3", label: "Monthly" },
						{ id: "4", label: "Rarely" },
						{ id: "5", label: "Never" },
					],
				},
				{
					id: "4",
					title:
						"What challenges, if any, have you encountered when working with these Bitcoin features?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Complexity of setup or integration" },
						{ id: "2", label: "Lack of knowledge or experience" },
						{ id: "3", label: "Limited documentation or support" },
						{ id: "4", label: "High transaction fees" },
						{ id: "5", label: "Compatibility with wallets or exchanges" },
						{ id: "6", label: "Lack of developer tools" },
						{ id: "7", label: "Other", isOther: true },
						{ id: "8", label: "None of the above", isNegative: true },
					],
				},
			],
		},
		{
			id: "2",
			title: "Wallets",
			description: "Bitcoin wallet preferences and backup practices",
			questions: [
				{
					id: "1",
					title: "Which wallet types have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Hardware Wallet (e.g., Ledger, Trezor)" },
						{ id: "2", label: "Software Wallet (e.g., Sparrow, Electrum)" },
						{ id: "3", label: "Mobile Wallet (e.g., BlueWallet, Muun)" },
						{ id: "4", label: "Custodial Wallet (e.g., Coinbase, Binance)" },
						{
							id: "5",
							label: "Non-Custodial Wallet (e.g., Green Wallet, Wasabi)",
						},
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "Which hardware wallets have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Ledger" },
						{ id: "2", label: "Trezor" },
						{ id: "3", label: "Coldcard" },
						{ id: "4", label: "BitBox" },
						{ id: "5", label: "Foundation Passport" },
						{ id: "6", label: "Keystone (formerly Cobo Vault)" },
						{ id: "7", label: "KeepKey" },
						{ id: "8", label: "SafePal S1" },
						{ id: "9", label: "Jade (by Blockstream)" },
						{ id: "10", label: "Other", isOther: true },
						{ id: "11", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which software wallets have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Electrum" },
						{ id: "2", label: "BlueWallet" },
						{ id: "3", label: "Muun" },
						{ id: "4", label: "Samourai" },
						{ id: "5", label: "Phoenix" },
						{ id: "6", label: "Green Wallet (Blockstream)" },
						{ id: "7", label: "Zeus" },
						{ id: "8", label: "Breez" },
						{ id: "9", label: "Wallet of Satoshi" },
						{ id: "10", label: "Edge" },
						{ id: "11", label: "BRD" },
						{ id: "12", label: "Mycelium" },
						{ id: "13", label: "Bitcoin Beach Wallet" },
						{ id: "14", label: "Simple Bitcoin Wallet" },
						{ id: "15", label: "Sparrow" },
						{ id: "16", label: "Wasabi" },
						{ id: "17", label: "Other", isOther: true },
						{ id: "18", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title: "How important is multisig support when choosing a wallet?",
					type: "radio",
					options: [
						{ id: "1", label: "Very important" },
						{ id: "2", label: "Somewhat important" },
						{ id: "3", label: "Not important" },
						{ id: "4", label: "No opinion" },
					],
				},
				{
					id: "5",
					title: "How do you typically store your wallet backup?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Paper backup" },
						{ id: "2", label: "Metal backup (e.g., Cryptosteel, Billfodl)" },
						{ id: "3", label: "Digital backup (e.g., encrypted file)" },
						{ id: "4", label: "Other", isOther: true },
						{ id: "5", label: "I don't back up my wallet", isNegative: true },
					],
				},
			],
		},
		{
			id: "3",
			title: "Exchanges & Fintech",
			description: "Experience with Bitcoin trading and financial services",
			questions: [
				{
					id: "1",
					title: "Which types of exchanges do you use?",
					type: "checkbox",
					options: [
						{
							id: "1",
							label:
								"Centralized Exchange (e.g., Coinbase, Gemini, Binance, Kraken)",
						},
						{
							id: "2",
							label: "Decentralized Exchange (e.g., Bisq, Hodl Hodl)",
						},
						{
							id: "3",
							label: "Peer-to-Peer Platforms (e.g., LocalBitcoins, Paxful)",
						},
						{ id: "4", label: "Other", isOther: true },
						{ id: "5", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "Which centralized exchanges have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Coinbase" },
						{ id: "2", label: "Binance" },
						{ id: "3", label: "Kraken" },
						{ id: "4", label: "Cash App" },
						{ id: "5", label: "River" },
						{ id: "6", label: "Gemini" },
						{ id: "7", label: "Crypto.com" },
						{ id: "8", label: "Robinhood" },
						{ id: "9", label: "Swan Bitcoin" },
						{ id: "10", label: "Strike" },
						{ id: "11", label: "Other", isOther: true },
						{ id: "12", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which decentralized / peer-to-peer exchanges have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Bisq" },
						{ id: "2", label: "Hodl Hodl" },
						{ id: "3", label: "RoboSats" },
						{ id: "4", label: "AgoraDesk" },
						{ id: "5", label: "LocalBitcoins" },
						{ id: "6", label: "Paxful" },
						{ id: "7", label: "Other", isOther: true },
						{ id: "8", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title:
						"What is your experience with withdrawing Bitcoin from centralized exchanges?",
					type: "radio",
					options: [
						{ id: "1", label: "Never had issues" },
						{ id: "2", label: "Occasional minor issues" },
						{ id: "3", label: "Frequent issues" },
						{ id: "4", label: "Major issues preventing withdrawals" },
						{ id: "5", label: "Never attempted to withdraw" },
					],
				},
				{
					id: "5",
					title:
						"How satisfied are you with the exchanges and custodial services you use?",
					type: "radio",
					options: [
						{ id: "1", label: "Never had issues" },
						{ id: "2", label: "Occasional minor issues" },
						{ id: "3", label: "Frequent issues" },
						{ id: "4", label: "Major issues preventing withdrawals" },
						{ id: "5", label: "Never attempted to withdraw" },
					],
				},
				{
					id: "6",
					title:
						"Do you primarily use custodial or non-custodial solutions for storing Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Mostly custodial" },
						{ id: "2", label: "Mostly non-custodial" },
						{ id: "3", label: "Mix of both" },
					],
				},
			],
		},
		{
			id: "4",
			title: "Lightning Network",
			description: "Usage of Layer 2 Bitcoin payment solutions",
			questions: [
				{
					id: "1",
					title: "Which Lightning Network wallets have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Muun" },
						{ id: "2", label: "Phoenix" },
						{ id: "3", label: "BlueWallet" },
						{ id: "4", label: "Wallet of Satoshi" },
						{ id: "5", label: "Alby Wallet" },
						{ id: "6", label: "Strike" },
						{ id: "7", label: "Breez" },
						{ id: "8", label: "Other", isOther: true },
						{ id: "9", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "Which platforms have you used for Lightning payments?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Strike" },
						{ id: "2", label: "LNBits" },
						{ id: "3", label: "Voltage Cloud" },
						{ id: "4", label: "BTCPay Server" },
						{ id: "5", label: "Breez" },
						{ id: "6", label: "Cash App" },
						{ id: "7", label: "Alby Hub" },
						{ id: "8", label: "Amboss Space" },
						{ id: "9", label: "Other", isOther: true },
						{ id: "10", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which Lightning Network tools have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "ThunderHub" },
						{ id: "2", label: "Ride The Lightning (RTL)" },
						{ id: "3", label: "Lightning Terminal (LiT)" },
						{ id: "4", label: "Balance of Satoshis (BOS)" },
						{ id: "5", label: "LNDg" },
						{ id: "6", label: "Charge-Lnd" },
						{ id: "7", label: "Lightning Polar" },
						{ id: "8", label: "LND Managebot" },
						{ id: "9", label: "Amboss" },
						{ id: "10", label: "Lightning Network+" },
						{ id: "11", label: "Lightning Pool" },
						{ id: "12", label: "Lightning Loop" },
						{ id: "13", label: "Plebnet tools" },
						{ id: "14", label: "Boltz Exchange" },
						{ id: "15", label: "Other", isOther: true },
						{ id: "16", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title: "What do you use the Lightning Network for?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Sending payments" },
						{ id: "2", label: "Receiving payments" },
						{ id: "3", label: "Online purchases" },
						{ id: "4", label: "In-person purchases" },
						{ id: "5", label: "Gaming" },
						{ id: "6", label: "Content creation" },
						{ id: "7", label: "Content consumption" },
						{ id: "8", label: "Streaming payments" },
						{ id: "9", label: "Podcasting 2.0" },
						{ id: "10", label: "Earning sats" },
						{ id: "11", label: "Trading" },
						{ id: "12", label: "Routing payments" },
						{ id: "13", label: "Testing/development" },
						{ id: "14", label: "Other", isOther: true },
						{ id: "15", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "5",
					title: "Which Lightning Network activities have you participated in?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Opened channels" },
						{ id: "2", label: "Closed channels" },
						{ id: "3", label: "Balanced channels" },
						{ id: "4", label: "Routing payments" },
						{ id: "5", label: "Channel management" },
						{ id: "6", label: "Fee management" },
						{ id: "7", label: "Submarine swaps" },
						{ id: "8", label: "Loop in/out" },
						{ id: "9", label: "Lightning Pool" },
						{ id: "10", label: "Dual funded channels" },
						{ id: "11", label: "HTLC management" },
						{ id: "12", label: "Watchtowers" },
						{ id: "13", label: "Lightning address setup" },
						{ id: "14", label: "Keysend payments" },
						{ id: "15", label: "AMP (Multi-path) payments" },
						{ id: "16", label: "LNURL implementation" },
						{ id: "17", label: "WebLN integration" },
						{ id: "18", label: "Other", isOther: true },
						{ id: "19", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "6",
					title: "What challenges do you face with the Lightning Network?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Channel management" },
						{ id: "2", label: "Fees" },
						{ id: "3", label: "Network reliability" },
						{ id: "4", label: "Wallet compatibility" },
						{ id: "5", label: "Privacy concerns" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
			],
		},
		{
			id: "5",
			title: "Development Tools",
			description: "Bitcoin development experience and tooling preferences",
			questions: [
				{
					id: "1",
					title:
						"Which programming languages do you use for Bitcoin development?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Python" },
						{ id: "2", label: "JavaScript/TypeScript" },
						{ id: "3", label: "C++" },
						{ id: "4", label: "Rust" },
						{ id: "5", label: "Go" },
						{ id: "6", label: "C# (.NET)" },
						{ id: "7", label: "Java" },
						{ id: "8", label: "Ruby" },
						{ id: "9", label: "Other", isOther: true },
						{ id: "10", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title:
						"Which Bitcoin development libraries or frameworks have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "bitcoinjs-lib" },
						{ id: "2", label: "BDK (Bitcoin Dev Kit)" },
						{ id: "3", label: "Libbitcoin" },
						{ id: "4", label: "btcd" },
						{ id: "5", label: "ElectrumX" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which Bitcoin Core features have you worked with?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Full Node" },
						{ id: "2", label: "Wallet Management" },
						{ id: "3", label: "RPC API" },
						{ id: "4", label: "PSBT (Partially Signed Bitcoin Transactions)" },
						{ id: "5", label: "Taproot Deployment" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title:
						"What is your experience with Bitcoin Improvement Proposals (BIPs)?",
					type: "radio",
					options: [
						{ id: "1", label: "Have authored one or more BIPs" },
						{ id: "2", label: "Have contributed to existing BIPs" },
						{ id: "3", label: "Have reviewed or commented on BIPs" },
						{ id: "4", label: "Familiar with BIPs but haven't contributed" },
						{ id: "5", label: "Not familiar with BIPs" },
					],
				},
				{
					id: "5",
					title: "Which testing environments do you use?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Testnet" },
						{ id: "2", label: "Regtest" },
						{ id: "3", label: "Signet" },
						{ id: "4", label: "Bitcoind JSON-RPC tests" },
						{ id: "5", label: "BIP174 PSBT Testing Tools" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "6",
					title:
						"How important is Bitcoin Core compatibility in your development work?",
					type: "radio",
					options: [
						{ id: "1", label: "Critical - must be compatible" },
						{ id: "2", label: "Important but not critical" },
						{ id: "3", label: "Somewhat important" },
						{ id: "4", label: "Not important" },
						{ id: "5", label: "Not applicable to my work" },
					],
				},
			],
		},
		{
			id: "6",
			title: "Nodes & Infrastructure",
			description: "Bitcoin node operation and network participation",
			questions: [
				{
					id: "1",
					title: "Which types of nodes have you run?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Bitcoin Core (Full Node)" },
						{ id: "2", label: "Pruned node (Bitcoin Core)" },
						{
							id: "3",
							label: "Lightning Network Node (e.g., LND, C-Lightning)",
						},
						{ id: "4", label: "ord" },
						{ id: "5", label: "btcd" },
						{ id: "6", label: "Electrum Server" },
						{ id: "7", label: "Other", isOther: true },
						{ id: "8", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "Which node management tools have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "MyNode" },
						{ id: "2", label: "Umbrel" },
						{ id: "3", label: "RaspiBlitz" },
						{ id: "4", label: "BTCPay Server" },
						{ id: "5", label: "Nodl" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which node monitoring tools have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "ThunderHub (Lightning node)" },
						{ id: "2", label: "Ride the Lightning (RTL)" },
						{ id: "3", label: "Specter" },
						{ id: "4", label: "Mempool.space" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title: "What is your experience with self-hosting block explorers?",
					type: "radio",
					options: [
						{ id: "1", label: "Currently self-hosting" },
						{ id: "2", label: "Previously self-hosted" },
						{ id: "3", label: "Planning to self-host" },
						{ id: "4", label: "Never self-hosted" },
						{ id: "5", label: "Not interested in self-hosting" },
					],
				},
				{
					id: "5",
					title: "How do you connect your wallet(s) to a Bitcoin node?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Directly (e.g., Sparrow with Bitcoin Core)" },
						{ id: "2", label: "Through Tor (e.g., Wasabi, Samourai)" },
						{ id: "3", label: "Via Electrum Personal Server" },
						{ id: "4", label: "Other", isOther: true },
						{
							id: "5",
							label: "I don't connect my wallet to a node",
							isNegative: true,
						},
					],
				},
				{
					id: "6",
					title: "Which privacy or networking tools do you use with your node?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Tor" },
						{ id: "2", label: "I2P" },
						{ id: "3", label: "VPN" },
						{ id: "4", label: "Other", isOther: true },
						{ id: "5", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "7",
					title: "How important is running your own Bitcoin node?",
					type: "radio",
					options: [
						{ id: "1", label: "Essential to my Bitcoin usage" },
						{ id: "2", label: "Important but not essential" },
						{ id: "3", label: "Nice to have" },
						{ id: "4", label: "Not important" },
						{ id: "5", label: "No opinion" },
					],
				},
			],
		},
		{
			id: "7",
			title: "Mining",
			description: "Bitcoin mining activities and hardware usage",
			questions: [
				{
					id: "1",
					title: "What type of Bitcoin mining have you participated in?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Home mining" },
						{ id: "2", label: "Industrial mining" },
						{ id: "3", label: "Cloud mining" },
						{ id: "4", label: "Mining pool operation" },
						{ id: "5", label: "Mining hardware development" },
						{ id: "6", label: "Mining software development" },
						{ id: "7", label: "Other", isOther: true },
						{ id: "8", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "Which mining hardware have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "ASIC miners" },
						{ id: "2", label: "GPU mining rigs" },
						{ id: "3", label: "CPU mining" },
						{ id: "4", label: "USB miners" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which mining pools have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Antpool" },
						{ id: "2", label: "F2Pool" },
						{ id: "3", label: "Foundry USA" },
						{ id: "4", label: "Binance Pool" },
						{ id: "5", label: "ViaBTC" },
						{ id: "6", label: "Poolin" },
						{ id: "7", label: "SlushPool (Braiins)" },
						{ id: "8", label: "MARA Pool" },
						{ id: "9", label: "Other", isOther: true },
						{ id: "10", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title: "What mining software have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "CGMiner" },
						{ id: "2", label: "BFGMiner" },
						{ id: "3", label: "Braiins OS" },
						{ id: "4", label: "MultiMiner" },
						{ id: "5", label: "Awesome Miner" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "5",
					title: "What is your primary motivation for mining Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Profit" },
						{ id: "2", label: "Network security" },
						{ id: "3", label: "Learning/experimentation" },
						{ id: "4", label: "Privacy (KYC-free bitcoin)" },
						{ id: "5", label: "Heat generation" },
						{ id: "6", label: "Other", isOther: true },
					],
				},
				{
					id: "6",
					title: "What challenges have you faced with Bitcoin mining?",
					type: "checkbox",
					options: [
						{ id: "1", label: "High electricity costs" },
						{ id: "2", label: "Hardware availability" },
						{ id: "3", label: "Heat management" },
						{ id: "4", label: "Noise management" },
						{ id: "5", label: "Technical complexity" },
						{ id: "6", label: "Regulatory concerns" },
						{ id: "7", label: "Profitability" },
						{ id: "8", label: "Other", isOther: true },
						{ id: "9", label: "None of the above", isNegative: true },
					],
				},
			],
		},
		{
			id: "8",
			title: "Privacy Tools",
			description: "Experience with Bitcoin privacy enhancement tools",
			questions: [
				{
					id: "1",
					title: "Which Bitcoin privacy tools have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Wasabi Wallet" },
						{ id: "2", label: "Samourai Wallet (before seizure)" },
						{ id: "3", label: "JoinMarket" },
						{ id: "4", label: "Whirlpool" },
						{ id: "5", label: "PayJoin" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "What is your experience with CoinJoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Regular user" },
						{ id: "2", label: "Occasional user" },
						{ id: "3", label: "Have tried it once" },
						{ id: "4", label: "Familiar but haven't used" },
						{ id: "5", label: "Not familiar" },
						{ id: "6", label: "Prefer not to answer" },
					],
				},
				{
					id: "3",
					title: "How would you rate the usability of Bitcoin privacy tools?",
					type: "radio",
					options: [
						{ id: "1", label: "Very easy to use" },
						{ id: "2", label: "Somewhat easy to use" },
						{ id: "3", label: "Neutral" },
						{ id: "4", label: "Somewhat difficult to use" },
						{ id: "5", label: "Very difficult to use" },
						{ id: "6", label: "Haven't used them" },
					],
				},
				{
					id: "4",
					title: "How important is Tor usage in your Bitcoin transactions?",
					type: "radio",
					options: [
						{ id: "1", label: "Essential for all transactions" },
						{ id: "2", label: "Important for some transactions" },
						{ id: "3", label: "Nice to have but not required" },
						{ id: "4", label: "Not important" },
						{ id: "5", label: "Don't use Tor" },
					],
				},
				{
					id: "5",
					title: "Which methods do you use to enhance Bitcoin privacy?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Coin Control" },
						{ id: "2", label: "Avoiding address reuse" },
						{ id: "3", label: "Tor" },
						{ id: "4", label: "Chain analysis countermeasures" },
						{ id: "5", label: "Multiple wallets" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "6",
					title: "What challenges have you encountered with privacy tools?",
					type: "checkbox",
					options: [
						{ id: "1", label: "High fees" },
						{ id: "2", label: "Low liquidity" },
						{ id: "3", label: "Technical difficulty" },
						{ id: "4", label: "Slow transaction times" },
						{ id: "5", label: "Compatibility issues" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
			],
		},
		{
			id: "9",
			title: "NFTs, Art, & Tokens",
			description: "Involvement with Bitcoin-based digital assets",
			questions: [
				{
					id: "1",
					title: "What is your experience with Bitcoin art?",
					type: "radio",
					options: [
						{ id: "1", label: "Active user/creator" },
						{ id: "2", label: "Have experimented with them" },
						{ id: "3", label: "Familiar but haven't used" },
						{ id: "4", label: "Not familiar" },
						{ id: "5", label: "Not interested" },
					],
				},
				{
					id: "2",
					title: "What is your experience with these ecosystems?",
					type: "checkbox",
					options: [
						{ id: "1", label: "BRC-20" },
						{ id: "2", label: "Runes" },
						{ id: "3", label: "Ordinals" },
						{ id: "4", label: "Counterparty" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "Not interested", isNegative: true },
					],
				},
				{
					id: "3",
					title: "Which Bitcoin art / tokens platforms have you used?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Ordinals Wallet" },
						{ id: "2", label: "Gamma.io" },
						{ id: "3", label: "Magic Eden" },
						{ id: "4", label: "UniSat" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title:
						"Which wallets have you used for Ordinals, Runes, and BRC-20s?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Sparrow Wallet" },
						{ id: "2", label: "Xverse Wallet" },
						{ id: "3", label: "Oyl Wallet" },
						{ id: "4", label: "Hiro Wallet" },
						{ id: "5", label: "UniSat Wallet" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "5",
					title:
						"Which Bitcoin-based art or NFT communities have you participated in?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Rare Pepe Community" },
						{ id: "2", label: "Taproot Wizards" },
						{ id: "3", label: "Quantum Cats" },
						{ id: "4", label: "Ordinals Community" },
						{ id: "5", label: "Counterparty Community" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "6",
					title: "How do you use Bitcoin art and tokens?",
					type: "checkbox",
					options: [
						{ id: "1", label: "As collectibles" },
						{ id: "2", label: "As a store of value" },
						{ id: "3", label: "For trading" },
						{ id: "4", label: "For art creation" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "Don't use them", isNegative: true },
					],
				},
				{
					id: "7",
					title:
						"What challenges have you encountered with Bitcoin art and tokens?",
					type: "checkbox",
					options: [
						{ id: "1", label: "High fees" },
						{ id: "2", label: "Low liquidity" },
						{ id: "3", label: "Lack of marketplaces" },
						{ id: "4", label: "Technical complexity" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "8",
					title:
						"How do you feel about the presence of art and NFTs on the Bitcoin blockchain?",
					type: "radio",
					options: [
						{ id: "1", label: "Very Negative" },
						{ id: "2", label: "Somewhat Negative" },
						{ id: "3", label: "Neutral" },
						{ id: "4", label: "Somewhat Positive" },
						{ id: "5", label: "Very Positive" },
					],
				},
			],
		},
		{
			id: "10",
			title: "Conferences & Community",
			description: "Participation in Bitcoin events and social groups",
			questions: [
				{
					id: "1",
					title: "Which Bitcoin conferences have you attended?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Baltic Honeybadger" },
						{ id: "2", label: "Bitcoin Amsterdam" },
						{ id: "3", label: "TABConf (Atlanta)" },
						{ id: "4", label: "Adopting Bitcoin (El Salvador)" },
						{ id: "5", label: "Bitcoin Conference (US)" },
						{ id: "6", label: "Unconfiscatable (Las Vegas)" },
						{ id: "7", label: "Bitcoin Mining Disrupt (Miami)" },
						{ id: "8", label: "Bitcoin++ (Austin)" },
						{ id: "9", label: "BitBlockBoom (Dallas)" },
						{ id: "10", label: "LaBitConf (Latin America)" },
						{ id: "11", label: "Bitcoin Africa Conference" },
						{ id: "12", label: "Bitcoin Austria Conference" },
						{ id: "13", label: "Advancing Bitcoin (London)" },
						{ id: "14", label: "Other", isOther: true },
						{ id: "15", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "What is your involvement with Bitcoin events?",
					type: "radio",
					options: [
						{ id: "1", label: "Regular speaker/organizer" },
						{ id: "2", label: "Occasional speaker/organizer" },
						{ id: "3", label: "Regular attendee" },
						{ id: "4", label: "Occasional attendee" },
						{ id: "5", label: "Virtual participant only" },
						{ id: "6", label: "No involvement" },
					],
				},
				{
					id: "3",
					title:
						"Which Bitcoin-related social media communities do you participate in?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Twitter/X" },
						{ id: "2", label: "BitcoinTalk" },
						{ id: "3", label: "Reddit" },
						{ id: "4", label: "Nostr" },
						{ id: "5", label: "Stacker News" },
						{ id: "6", label: "Telegram groups" },
						{ id: "7", label: "Mastodon" },
						{ id: "8", label: "Discord" },
						{ id: "9", label: "Signal groups" },
						{ id: "10", label: "LinkedIn" },
						{ id: "11", label: "Other", isOther: true },
						{ id: "12", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "4",
					title: "Which Bitcoin newsletters do you read?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Bitcoin Optech" },
						{ id: "2", label: "The Bitcoin Times" },
						{ id: "3", label: "Nakamoto" },
						{ id: "4", label: "Satoshi's Journal" },
						{ id: "5", label: "The Daily Bit" },
						{ id: "6", label: "Marty's Bent" },
						{ id: "7", label: "Bitcoin Magazine Pro" },
						{ id: "8", label: "Other", isOther: true },
						{ id: "9", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "5",
					title: "Which Bitcoin podcasts do you listen to?",
					type: "checkbox",
					options: [
						{ id: "1", label: "What Bitcoin Did Podcast / Mr. Obnoxious" },
						{ id: "2", label: "Tales from the Crypt" },
						{ id: "3", label: "Rabbit Hole Recap" },
						{ id: "4", label: "Citadel Dispatch" },
						{ id: "5", label: "Bitcoin Audible" },
						{ id: "6", label: "Stephan Livera Podcast" },
						{ id: "7", label: "Bitcoin Magazine Podcast" },
						{ id: "8", label: "The Mempool" },
						{ id: "9", label: "Other", isOther: true },
						{ id: "10", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "6",
					title: "How do you prefer to engage with the Bitcoin community?",
					type: "radio",
					options: [
						{ id: "1", label: "Primarily in-person events" },
						{ id: "2", label: "Primarily online communities" },
						{ id: "3", label: "Mix of online and in-person" },
						{ id: "4", label: "Passive consumption only" },
						{ id: "5", label: "Don't engage with the community" },
					],
				},
			],
		},
		{
			id: "11",
			title: "Learning Resources",
			description: "Bitcoin education and knowledge acquisition methods",
			questions: [
				{
					id: "1",
					title: "How do you learn about Bitcoin?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Books" },
						{ id: "2", label: "Online tutorials" },
						{ id: "3", label: "Video courses" },
						{ id: "4", label: "Podcasts" },
						{ id: "5", label: "Technical documentation" },
						{ id: "6", label: "Community discussions" },
						{ id: "7", label: "Other", isOther: true },
						{ id: "8", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "2",
					title: "Which Bitcoin books have you read?",
					type: "checkbox",
					options: [
						{ id: "1", label: '"The Bitcoin Standard" by Saifedean Ammous' },
						{ id: "2", label: '"Mastering Bitcoin" by Andreas Antonopoulos' },
						{ id: "3", label: '"Inventing Bitcoin" by Yan Pritzker' },
						{
							id: "4",
							label: '"The Bullish Case for Bitcoin" by Vijay Boyapati',
						},
						{ id: "5", label: '"The Price of Tomorrow" by Jeff Booth' },
						{ id: "6", label: '"Layered Money" by Nik Bhatia' },
						{ id: "7", label: '"Programming Bitcoin" by Jimmy Song' },
						{ id: "8", label: "Other", isOther: true },
						{ id: "9", label: "None of the above", isNegative: true },
					],
				},
				{
					id: "3",
					title: "What is your experience with Bitcoin development courses?",
					type: "radio",
					options: [
						{ id: "1", label: "Have completed multiple courses" },
						{ id: "2", label: "Have completed one course" },
						{ id: "3", label: "Currently enrolled in course(s)" },
						{ id: "4", label: "Planning to take courses" },
						{ id: "5", label: "No interest in development courses" },
					],
				},
				{
					id: "4",
					title: "What challenges do you face when learning about Bitcoin?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Finding updated information" },
						{ id: "2", label: "Understanding technical concepts" },
						{ id: "3", label: "Lack of time" },
						{ id: "4", label: "High cost of courses" },
						{ id: "5", label: "Information overload" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "No significant challenges", isNegative: true },
					],
				},
			],
		},
		{
			id: "12",
			title: "About You",
			description: "Demographics and personal Bitcoin journey details",
			questions: [
				{
					id: "1",
					title: "How long have you been involved with Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Less than 1 year" },
						{ id: "2", label: "1-2 years" },
						{ id: "3", label: "3-5 years" },
						{ id: "4", label: "More than 5 years" },
					],
				},
				{
					id: "2",
					title: "What is your primary involvement with Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Investor/Holder" },
						{ id: "2", label: "Developer" },
						{ id: "3", label: "Educator" },
						{ id: "4", label: "Content creator" },
						{ id: "5", label: "Entrepreneur" },
						{ id: "6", label: "Miner" },
						{ id: "7", label: "Other", isOther: true },
					],
				},
				{
					id: "3",
					title: "How frequently do you use Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Daily" },
						{ id: "2", label: "Weekly" },
						{ id: "3", label: "Monthly" },
						{ id: "4", label: "Rarely" },
						{ id: "5", label: "Never" },
					],
				},
				{
					id: "4",
					title: "How would you describe your technical knowledge of Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Beginner" },
						{ id: "2", label: "Intermediate" },
						{ id: "3", label: "Advanced" },
						{ id: "4", label: "Expert" },
					],
				},
				{
					id: "5",
					title: "What is your current profession or primary role?",
					type: "radio",
					options: [
						{ id: "1", label: "Developer/Engineer" },
						{ id: "2", label: "Researcher/Academic" },
						{ id: "3", label: "Investor" },
						{ id: "4", label: "Educator/Content Creator" },
						{ id: "5", label: "Community Organizer" },
						{ id: "6", label: "Financial Services Professional" },
						{ id: "7", label: "Miner" },
						{ id: "8", label: "Entrepreneur" },
						{ id: "9", label: "Other", isOther: true },
					],
				},
				{
					id: "6",
					title: "What is your age range?",
					type: "radio",
					options: [
						{ id: "1", label: "Under 18" },
						{ id: "2", label: "18-24" },
						{ id: "3", label: "25-34" },
						{ id: "4", label: "35-44" },
						{ id: "5", label: "45-54" },
						{ id: "6", label: "55-64" },
						{ id: "7", label: "65+" },
						{ id: "8", label: "Prefer not to say" },
					],
				},
				{
					id: "7",
					title: "What is your highest level of education?",
					type: "radio",
					options: [
						{ id: "1", label: "High school or equivalent" },
						{ id: "2", label: "Associate's degree" },
						{ id: "3", label: "Bachelor's degree" },
						{ id: "4", label: "Master's degree" },
						{ id: "5", label: "PhD or equivalent" },
						{ id: "6", label: "Other", isOther: true },
						{ id: "7", label: "Prefer not to say" },
					],
				},
				{
					id: "8",
					title: "In which country do you currently reside?",
					type: "text",
				},
				{
					id: "9",
					title: "What is your gender?",
					type: "radio",
					options: [
						{ id: "1", label: "Male" },
						{ id: "2", label: "Female" },
						{ id: "3", label: "Other", isOther: true },
						{ id: "4", label: "Prefer not to say" },
					],
				},
				{
					id: "10",
					title: "How would you describe your political views?",
					type: "radio",
					options: [
						{ id: "1", label: "Conservative" },
						{ id: "2", label: "Liberal" },
						{ id: "3", label: "Libertarian" },
						{ id: "4", label: "Apolitical" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "Prefer not to say" },
					],
				},
				{
					id: "11",
					title: "What is your level of engagement with Bitcoin communities?",
					type: "radio",
					options: [
						{ id: "1", label: "Very engaged (daily participation)" },
						{ id: "2", label: "Moderately engaged (weekly participation)" },
						{ id: "3", label: "Occasionally engaged (monthly participation)" },
						{ id: "4", label: "Rarely engaged" },
						{ id: "5", label: "Not engaged" },
					],
				},
				{
					id: "12",
					title: "What is your primary motivation for using Bitcoin?",
					type: "radio",
					options: [
						{ id: "1", label: "Investment/Store of value" },
						{ id: "2", label: "Technology interest" },
						{ id: "3", label: "Financial sovereignty" },
						{ id: "4", label: "Privacy and freedom" },
						{ id: "5", label: "Professional development" },
						{ id: "6", label: "Other", isOther: true },
					],
				},
				{
					id: "13",
					title: "Have you used other cryptocurrencies?",
					type: "checkbox",
					options: [
						{ id: "1", label: "Ethereum" },
						{ id: "2", label: "Solana" },
						{ id: "3", label: "BNB" },
						{ id: "4", label: "Stablecoins (USDC, USDT, etc)" },
						{ id: "5", label: "Other", isOther: true },
						{ id: "6", label: "Bitcoin only", isNegative: true },
						{ id: "7", label: "None", isNegative: true },
					],
				},
				{
					id: "14",
					title: "What is your annual income range?",
					type: "radio",
					options: [
						{ id: "1", label: "Under $25,000" },
						{ id: "2", label: "25,000–$50,000" },
						{ id: "3", label: "50,000–$100,000" },
						{ id: "4", label: "100,000–$250,000" },
						{ id: "5", label: "Over $250,000" },
						{ id: "6", label: "Prefer not to say" },
					],
				},
				{
					id: "15",
					title: "What best describes your Bitcoin strategy?",
					type: "radio",
					options: [
						{ id: "1", label: "Long-term holder (HODL)" },
						{ id: "2", label: "Active trader" },
						{ id: "3", label: "Developer/Builder" },
						{ id: "4", label: "Privacy-focused user" },
						{ id: "5", label: "Other", isOther: true },
					],
				},
				{
					id: "16",
					title: "What is your relationship with Bitcoin maximalism?",
					type: "radio",
					options: [
						{ id: "1", label: "Strong Bitcoin maximalist" },
						{ id: "2", label: "Moderate Bitcoin maximalist" },
						{ id: "3", label: "Bitcoin-preferred but not maximalist" },
						{ id: "4", label: "Cryptocurrency generalist" },
						{ id: "5", label: "Not familiar with the term" },
						{ id: "6", label: "Prefer not to say" },
					],
				},
				{
					id: "17",
					title: "Where did you hear about this survey?",
					type: "text",
				},
				{
					id: "18",
					title: "How could this survey be improved?",
					type: "text",
				},
				{
					id: "19",
					title:
						"Would you like to be notified when the survey results are released?",
					type: "radio",
					options: [
						{ id: "1", label: "Yes (will provide email on next page)" },
						{ id: "2", label: "No" },
					],
				},
			],
		},
	],
} satisfies Survey;
